apiVersion: apps/v1
kind: Deployment
metadata:
  name: allianceauth-beat
  labels:
    app: allianceauth-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: allianceauth-beat
  template:
    metadata:
      labels:
        app: allianceauth-beat
    spec:
      containers:
        - name: allianceauth
          image: registry.gitlab.com/allianceauth/allianceauth/auth:v4.13.0 # {"$imagepolicy": "flux-system:allianceauth"}
          command:
            - sh
            - -c
          args:
            - mkdir -p /home/allianceauth/log && pip install --upgrade -r /home/allianceauth/myauth/requirements.txt && exec celery -A myauth beat
          envFrom:
            - secretRef:
                name: allianceauth-env
                optional: true
          volumeMounts:
            - name: config
              mountPath: /home/allianceauth/myauth
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
