apiVersion: apps/v1
kind: Deployment
metadata:
  name: allianceauth-worker
  labels:
    app: allianceauth-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: allianceauth-worker
  template:
    metadata:
      labels:
        app: allianceauth-worker
    spec:
      containers:
        - name: allianceauth
          workingDir: /home/allianceauth/myauth
          image: registry.gitlab.com/allianceauth/allianceauth/auth:v4.13.0 # {"$imagepolicy": "flux-system:allianceauth"}
          command:
            - sh
            - -c
          args:
            - mkdir -p /home/allianceauth/log && pip install --upgrade -r /home/allianceauth/myauth/requirements.txt && exec celery -A myauth worker --pool=threads --concurrency=5 -n worker_%n
          envFrom:
            - secretRef:
                name: allianceauth-env
                optional: true
          volumeMounts:
            - name: config
              mountPath: /home/allianceauth/myauth
            - name: static
              mountPath: /var/www/myauth/static
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: allianceauth-config
        - name: static
          persistentVolumeClaim:
            claimName: allianceauth-static
