apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap-myauth-overrides.yaml
  - configmap-nginx.yaml
  - pvc-static.yaml
  - service-gunicorn.yaml
  - service-nginx.yaml
  - deployment-gunicorn.yaml
  - deployment-worker.yaml
  - deployment-beat.yaml
  - deployment-nginx.yaml
