apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gameservers
resources:
  - namespace.yaml
  - ../../../apps/minecraft
  - minecraft-config.yaml

patchesStrategicMerge:
  - patches/minecraft-service.yaml
  - patches/minecraft.yaml
