apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: immichframe
spec:
  image: ghcr.io/immichframe/immichframe
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: immichframe
spec:
  imageRepositoryRef:
    name: immichframe
  filterTags:
    pattern: '^v?(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)\.(?P<rev>\d+)$'
    extract: '$major.$minor.$patch-$rev'
  policy:
    semver:
      range: ">=1.0.31-0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immichframe
  labels:
    app: immichframe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immichframe
  template:
    metadata:
      labels:
        app: immichframe
    spec:
      containers:
        - name: immichframe
          image: ghcr.io/immichframe/immichframe:v1.0.31.0 # {"$imagepolicy": "immichframe"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /app/Config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: immichframe-config