apiVersion: apps/v1
kind: Deployment
metadata:
  name: immichframe
  labels:
    app: immichframe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immichframe
  template:
    metadata:
      labels:
        app: immichframe
    spec:
      containers:
        - name: immichframe
          image: ghcr.io/immichframe/immichframe:v1.0.31.0 # {"$imagepolicy": "flux-system:immichframe"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /app/Config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: immichframe-config