apiVersion: v1
kind: Service
metadata:
  name: immichframe
  labels:
    app: immichframe
spec:
  type: ClusterIP
  selector:
    app: immichframe
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP