apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - allianceauth.yaml
  - cloudflared.yaml
  - frigate.yaml
  - homeassistant.yaml
  - immich.yaml
  - immich-ml.yaml
  - immichframe.yaml
  - mosquitto.yaml
  - npm-wg.yaml
  - open-webui.yaml
  - ollama.yaml
  - redis.yaml
  - technitium.yaml
  - vaultwarden.yaml
  - zigbee2mqtt.yaml
  - minecraft.yaml
