apiVersion: v1
kind: Secret
metadata:
    name: immich-redis-config
type: Opaque
stringData:
    host: ENC[AES256_GCM,data:VSEcMqqc+zx4tmWE7inGEF1S5B3Nz4tVv1+Ac0TD2fMB,iv:SODH7iCd8Sk44l9POVZdR/V+YpeE0kUpM3sr3TWnonI=,tag:W0RUkn0C7xBQX/5VwbH/jg==,type:str]
    port: ENC[AES256_GCM,data:nyMeJQ==,iv:flV9t1x8D+fbcRzbBJZRjg+yglub8vsbp1rJ/OINFBE=,tag:zJmPPU4VJ69+BV6Q7Sa+DA==,type:str]
sops:
    age:
        - recipient: age1gfg2cjnueyul65k0sdd3x85t2n6tlnspmfe7g87xzjt6f86y2fas63kt3x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVEJ5d0dtNVQwbXNYM2tr
            WW9xdmRnMmZhaVdJOU9nSU1xb1ZTempLVVMwCnQ1elFEM2dibzd3dnlicXdWaGpV
            azdVTVlLZHgvdVFYcDRYc21xOE4zUWsKLS0tIDgwUUplcjRwTlczUUkyeGFHMmJ1
            Y2ZNQ2pkeVQ2VUJYajQvTzVUTm9vcjAKa9jYGT+eswInHMq9gdCJbSjom6ivLJCF
            GRVytKnPLA7dqELKXP2foP2bYqE20nW+5ms/XbHfpxgLeBs9F3kOcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T00:28:07Z"
    mac: ENC[AES256_GCM,data:8ICUP9mVQJaVn7Jz0eI70dDdYgc2t9sojttDrW9VyXwfApX9wKJ+rrG+ksw9FWPEo2AomFs7mpBji1+UavSo6CuqZjqh/dgU61YdFmNK5XsxPMuvdSk5KJJsGrwNmPF8YXMcuAyDe2++0+wbGaMQqbc+sgb+yyQlQZmxF5jae88=,iv:5Ym4913aW9/Pu3iPagTYHUw3KlKMB+tMliTnHZBNLQI=,tag:oavaTchyvwZNHEZH0z6BMQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
