apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: prod-services
  namespace: metallb
spec:
  avoidBuggyIPs: true
  addresses:
  - 10.1.1.1/24
  - fd7a:6e5b:cafe:cafe:10:1::1/112
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: test-services
  namespace: metallb
spec:
  avoidBuggyIPs: true
  addresses:
  - 10.1.2.1/24
  - fd7a:6e5b:cafe:cafe:10:2::1/112
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisment
  namespace: metallb
spec:
  ipAddressPools:
  - prod-services
  - test-services