apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: home-net
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "bond0.15",
      "mode": "bridge",
      "mtu": 1500,
      "ipam": {
        "type": "static"
      }
    }