apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: home-net
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "master": "bond0.15",
      "ipam": {
        "type": "static",
        "routes": [
          { "dst": "172.16.15.0/24", "gw": "172.16.15.1" }
        ]
      }
    }