apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infra-controllers.yaml
  - infra-configs.yaml
  - app-tunnels.yaml
  - app-databases.yaml
  - app-micasa.yaml
  - app-mrakaki.yaml
  - app-monitoring.yaml