apiVersion: v1
kind: Service
metadata:
  name: technitium-dns
spec:
  type: LoadBalancer
  selector:
    app: technitium-dns
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: dns-udp
    port: 53
    protocol: UDP
  - name: admin-https
    port: 53443
    protocol: TCP
