apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tunnels
resources:
  - namespace.yaml

  - secrets-cloudflared.yaml
  - ../../../apps/cloudflared

  - npm-secret.yaml
  - ../../../apps/npm
patchesStrategicMerge:
  - patches/npm.yaml
  - patches/npm-service.yaml