apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tunnels
resources:
  - namespace.yaml
  - secrets-cloudflared.yaml
  - secrets-pangolin.yaml
  - ../../../apps/pangolin
  - ../../../apps/cloudflared
