apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tunnels
resources:
  - namespace.yaml
  - secrets-cloudflared.yaml
  - npm-wg-secret.yaml
  - ../../../apps/cloudflared
  - ../../../apps/npm-wg
patchesStrategicMerge:
  - patches/npm-wg.yaml