apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: databases
resources:
  - namespace.yaml
  - secrets.yaml
  - ../../../apps/postgres
  - ../../../apps/redis
patchesStrategicMerge:
  - patches/postgres-server.yaml
  - patches/postgres-service.yaml