apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - server.yaml
  - service.yaml
  - service-headless.yaml
  - model-config.yaml
  - pvc-models.yaml
  - job-download-model.yaml

