apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - node-feature-discovery/repository.yaml
  - node-feature-discovery/release.yaml

  - rook/namespace.yaml
  - rook/repository.yaml
  - rook/release.yaml

  - metallb/namespace.yaml
  - metallb/repository.yaml
  - metallb/release.yaml

  - multus/release.yaml
  