apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # K3S auto upgrade controller
  - https://github.com/rancher/system-upgrade-controller/releases/latest/download/crd.yaml
  - https://github.com/rancher/system-upgrade-controller/releases/latest/download/system-upgrade-controller.yaml


  - node-feature-discovery/repository.yaml
  - node-feature-discovery/release.yaml

  - rook/namespace.yaml
  - rook/repository.yaml
  - rook/release.yaml

  - metallb/namespace.yaml
  - metallb/repository.yaml
  - metallb/release.yaml

  - multus/release.yaml
  
  - kyverno/namespace.yaml
  - kyverno/repository.yaml
  - kyverno/release.yaml
  