apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sspti
resources:
  - namespace.yaml
  - allianceauth-env.yaml
  - llmcord-config.yaml
  - ../../../apps/allianceauth
  - ../../../apps/llmcord

patchesStrategicMerge:
  - patches/allianceauth-storage.yaml
  - patches/allianceauth-requirements.yaml
  - patches/llmcord-storage.yaml
