apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sspti
resources:
  - namespace.yaml
  - allianceauth-env.yaml
  - ../../../apps/allianceauth

patchesStrategicMerge:
  - patches/allianceauth-storage.yaml
  - patches/allianceauth-requirements.yaml
