apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  - rook/cluster.yaml
  - rook/toolbox.yaml
  - rook/storageclass-cephfs.yaml
  - rook/storageclass-rbd.yaml
  - metallb/config.yaml
