apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  - node-feature-discovery/rule-coral-tpu.yaml

  - rook/cluster.yaml
  - rook/toolbox.yaml
  - rook/storageclass-cephfs.yaml
  - rook/storageclass-rbd.yaml

  - metallb/peers.yaml
  - metallb/pools.yaml
  - metallb/advertisement.yaml

  - multus/cctv-net.yaml
  - multus/home-net.yaml
  - multus/iot-net.yaml
  
  - kyverno/timezone-policy.yaml

  - k3s-upgrade/server.yaml
  - k3s-upgrade/agent.yaml