apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  - node-feature-discovery/rule-coral-tpu.yaml

  - rook/cluster.yaml
  - rook/toolbox.yaml
  - rook/storageclass-cephfs.yaml
  - rook/storageclass-rbd.yaml

  - metallb/config.yaml

  - multus/cctv-net.yaml
  - multus/home-net.yaml
  
  - kyverno/timezone-policy.yaml